name: build gh-pages
'on': [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - {name: Checkout repo, uses: actions/checkout@v3}
    - name: Node Setup
      uses: actions/setup-node@v3
      with: {node-version: 16.x}
    - name: Deploy gh-pages
      run: |-
        make build-web
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        cd web-build && git init && git add -A && git commit -m 'deploying to gh-pages'
        git remote add origin git@github.com:zcaudate/foundation.react-native.git
        git push origin HEAD:gh-pages --force
